Refs #20318: Desperate times call for desperate measures
Signed-off-by: EduPonz <eduardoponz@eprosima.com>

diff --git a/.github/workflows/reusable-windows-ci.yml b/.github/workflows/reusable-windows-ci.yml
--- a/.github/workflows/reusable-windows-ci.yml
+++ b/.github/workflows/reusable-windows-ci.yml
@@ -46,51 +46,65 @@ jobs:
           path: src/fastrtps
           submodules: true
 
+      - name: Sync foonathan/memory repository
+        uses: eProsima/eProsima-CI/external/checkout@v0
+        with:
+          repository: foonathan/memory
+          ref: v0.7-3
+          path: src/foonathan_memory
+
+      - name: Sync eProsima/Fast-CDR repository
+        uses: eProsima/eProsima-CI/external/checkout@v0
+        with:
+          repository: eProsima/Fast-CDR
+          ref: master
+          path: src/fastcdr
+
       - name: Get minimum supported version of CMake
         uses: lukka/get-cmake@latest
         with:
           cmakeVersion: '3.22.6'
 
-      - name: Install OpenSSL
-        uses: eProsima/eprosima-CI/windows/install_openssl@v0
-        with:
-          version: '3.1.1'
+      # - name: Install OpenSSL
+      #   uses: eProsima/eprosima-CI/windows/install_openssl@v0
+      #   with:
+      #     version: '3.1.1'
 
-      - name: Update OpenSSL environment variables
-        run: |
-          # Update the environment
-          if (Test-Path -Path $Env:ProgramW6432\OpenSSL)
-          {
-            "OPENSSL64_ROOT=$Env:ProgramW6432\OpenSSL" | Out-File $Env:GITHUB_ENV -Append -Encoding OEM
-            Set-Item -Force -Path "Env:PATH" -Value "$Env:PATH;$Env:ProgramW6432\OpenSSL"
-            "PATH=$Env:PATH" | Out-File $Env:GITHUB_ENV -Append -Encoding OEM
-          }
-          elseif (Test-Path -Path $Env:ProgramW6432\OpenSSL-Win)
-          {
-            "OPENSSL64_ROOT=$Env:ProgramW6432\OpenSSL-Win" | Out-File $Env:GITHUB_ENV -Append -Encoding OEM
-            Set-Item -Force -Path "Env:PATH" -Value "$Env:PATH;$Env:ProgramW6432\OpenSSL-Win"
-            "PATH=$Env:PATH" | Out-File $Env:GITHUB_ENV -Append -Encoding OEM
-          }
-          elseif (Test-Path -Path $Env:ProgramW6432\OpenSSL-Win64)
-          {
-            "OPENSSL64_ROOT=$Env:ProgramW6432\OpenSSL-Win64" | Out-File $Env:GITHUB_ENV -Append -Encoding OEM
-            Set-Item -Force -Path "Env:PATH" -Value "$Env:PATH;$Env:ProgramW6432\OpenSSL-Win64"
-            "PATH=$Env:PATH" | Out-File $Env:GITHUB_ENV -Append -Encoding OEM
-          }
-          else
-          {
-            Write-Error -Message "Cannot find OpenSSL installation."
-            exit 1
-          }
+      # - name: Update OpenSSL environment variables
+      #   run: |
+      #     # Update the environment
+      #     if (Test-Path -Path $Env:ProgramW6432\OpenSSL)
+      #     {
+      #       "OPENSSL64_ROOT=$Env:ProgramW6432\OpenSSL" | Out-File $Env:GITHUB_ENV -Append -Encoding OEM
+      #       Set-Item -Force -Path "Env:PATH" -Value "$Env:PATH;$Env:ProgramW6432\OpenSSL"
+      #       "PATH=$Env:PATH" | Out-File $Env:GITHUB_ENV -Append -Encoding OEM
+      #     }
+      #     elseif (Test-Path -Path $Env:ProgramW6432\OpenSSL-Win)
+      #     {
+      #       "OPENSSL64_ROOT=$Env:ProgramW6432\OpenSSL-Win" | Out-File $Env:GITHUB_ENV -Append -Encoding OEM
+      #       Set-Item -Force -Path "Env:PATH" -Value "$Env:PATH;$Env:ProgramW6432\OpenSSL-Win"
+      #       "PATH=$Env:PATH" | Out-File $Env:GITHUB_ENV -Append -Encoding OEM
+      #     }
+      #     elseif (Test-Path -Path $Env:ProgramW6432\OpenSSL-Win64)
+      #     {
+      #       "OPENSSL64_ROOT=$Env:ProgramW6432\OpenSSL-Win64" | Out-File $Env:GITHUB_ENV -Append -Encoding OEM
+      #       Set-Item -Force -Path "Env:PATH" -Value "$Env:PATH;$Env:ProgramW6432\OpenSSL-Win64"
+      #       "PATH=$Env:PATH" | Out-File $Env:GITHUB_ENV -Append -Encoding OEM
+      #     }
+      #     else
+      #     {
+      #       Write-Error -Message "Cannot find OpenSSL installation."
+      #       exit 1
+      #     }
 
       # TODO: check arguments
-      - name: Install colcon
-        uses: eProsima/eProsima-CI/windows/install_colcon@v0
+      # - name: Install colcon
+      #   uses: eProsima/eProsima-CI/windows/install_colcon@v0
 
-      - name: Install Python dependencies
-        uses: eProsima/eProsima-CI/windows/install_python_packages@v0
-        with:
-          packages: vcstool xmlschema
+      # - name: Install Python dependencies
+      #   uses: eProsima/eProsima-CI/windows/install_python_packages@v0
+      #   with:
+      #     packages: vcstool xmlschema
 
       # - name: Install asio and tinyxml2
       #   run: |
@@ -117,83 +131,125 @@ jobs:
 
           New-Item -ItemType File googletest/COLCON_IGNORE
 
-      - name: Prepare colcon workspace
-        run: |
-          # Get some convenient tools
-          Install-Module -Name ConvertBase64Strings -Force -AllowClobber
-          Import-Module -name ConvertBase64Strings -Prefix CI
-          Install-Module powershell-yaml -Force
+      # - name: Prepare colcon workspace
+      #   run: |
+      #     # Get some convenient tools
+      #     Install-Module -Name ConvertBase64Strings -Force -AllowClobber
+      #     Import-Module -name ConvertBase64Strings -Prefix CI
+      #     Install-Module powershell-yaml -Force
 
-          # Nightly job
-          if ("${{ inputs.label }}".Contains("nightly"))
-          {
-              $depends_repos_path = ".\src\fastrtps\.github\workflows\config\nightly_${{ inputs.fastdds_branch }}.repos"
-              if (!(Test-Path -Path $depends_repos_path))
-              {
-                $depends_repos_path = ".\src\fastrtps\.github\workflows\config\nightly_master.repos"
-              }
-              $meta_path = ".\src\fastrtps\.github\workflows\config\nightly.meta"
-          }
-          # Either PR or manual
-          else
-          {
-              $depends_repos_path = ".\src\fastrtps\.github\workflows\config\default_ci_${{ inputs.fastdds_branch }}.repos"
-              if (!(Test-Path -Path $depends_repos_path))
-              {
-                $depends_repos_path = ".\src\fastrtps\.github\workflows\config\default_ci_master.repos"
-              }
-              $meta_path = ".\src\fastrtps\.github\workflows\config\default_ci.meta"
-          }
-          Write-Output "Selected repos files: $depends_repos_path"
-          Write-Output "Selected metas files: $meta_path"
+      #     # Nightly job
+      #     if ("${{ inputs.label }}".Contains("nightly"))
+      #     {
+      #         $depends_repos_path = ".\src\fastrtps\.github\workflows\config\nightly_${{ inputs.fastdds_branch }}.repos"
+      #         if (!(Test-Path -Path $depends_repos_path))
+      #         {
+      #           $depends_repos_path = ".\src\fastrtps\.github\workflows\config\nightly_master.repos"
+      #         }
+      #         $meta_path = ".\src\fastrtps\.github\workflows\config\nightly.meta"
+      #     }
+      #     # Either PR or manual
+      #     else
+      #     {
+      #         $depends_repos_path = ".\src\fastrtps\.github\workflows\config\default_ci_${{ inputs.fastdds_branch }}.repos"
+      #         if (!(Test-Path -Path $depends_repos_path))
+      #         {
+      #           $depends_repos_path = ".\src\fastrtps\.github\workflows\config\default_ci_master.repos"
+      #         }
+      #         $meta_path = ".\src\fastrtps\.github\workflows\config\default_ci.meta"
+      #     }
+      #     Write-Output "Selected repos files: $depends_repos_path"
+      #     Write-Output "Selected metas files: $meta_path"
 
-          # Generate the meta file
-          "::group::deployed colcon.meta file"
-          $meta = Get-Content $meta_path | ConvertFrom-Yaml
-          $meta | ConvertTo-Json -Depth 3 | Tee-Object -FilePath ci.meta -Encoding OEM
-          "::endgroup::"
+      #     # Generate the meta file
+      #     "::group::deployed colcon.meta file"
+      #     $meta = Get-Content $meta_path | ConvertFrom-Yaml
+      #     $meta | ConvertTo-Json -Depth 3 | Tee-Object -FilePath ci.meta -Encoding OEM
+      #     "::endgroup::"
 
-          # create source dir and download the sources
-          vcs import src --input $depends_repos_path --skip-existing
+      #     # create source dir and download the sources
+      #     vcs import src --input $depends_repos_path --skip-existing
 
       - name: Build
         id: build
         continue-on-error: false
-        uses: eProsima/eProsima-CI/windows/colcon_build@v0
-        with:
-          colcon_meta_file: ${{ github.workspace }}/ci.meta
-          colcon_build_args: --merge-install ${{ inputs.colcon-args }}
-          cmake_args: --no-warn-unused-cli ${{ inputs.cmake-args }}
-          cmake_args_default: -DCMAKE_PREFIX_PATH='C:/Program Files/googletest/lib/cmake/GTest' -DGTest_DIR='C:/Program Files/googletest/lib/cmake/GTest' -DCMAKE_CXXFLAGS="/MP /WX"
-          cmake_build_type: ${{ matrix.cmake-config }}
-          workspace: ${{ github.workspace }}
-
-      - name: Test
-        if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-test') &&
-                (
-                  steps.build.outcome == 'success' &&
-                  (
-                    steps.build.outputs.BuildWarningsErrors == 0 ||
-                    contains(steps.build.outputs.BuildWarningsErrors, 'warning')
-                  )
-                ) }}
-        id: test
         run: |
-          # Create a junit file for test results
-          $junit = New-Item -Path ./junit.xml -ItemType File
-          'JUNIT_LOG=' + $junit.FullName | Out-File $Env:GITHUB_ENV -Append -Encoding OEM
 
-          # add ctest args
-          $ctestargs = '${{ inputs.ctest-args }}'.split(" ")
+          "::group::Load VS prompt"
 
-          # Show the arguments
-          EchoArgs --packages-select fastrtps --event-handlers=console_direct+ `
-            --merge-install --ctest-args $ctestargs --repeat until-pass:3 `
-            --timeout 300 --output-junit $junit
+          # Microsoft.VisualStudio.DevShell.dll file in the Visual Studio installation directories,
+          # imports the associated PowerShell module,
+          # and launches the Visual Studio development shell with the specified options
+          ls -Path @(${Env:ProgramFiles},${Env:ProgramFiles(x86)}) -Filter '*Visual Studio*' -Directory  -ErrorAction SilentlyContinue |
+          ls -R -Filter 'Microsoft.VisualStudio.DevShell.dll' | select -First 1 -OutVariable pwshmodule ; `
+            Import-Module $pwshmodule;Enter-VsDevShell -SetDefaultWindowTitle -VsInstallPath $pwshmodule.Directory.Parent.Parent `
+            -StartInPath (pwd) -DevCmdArguments '/arch=x64 /host_arch=x64'
 
-          # Run the testing
-          "::group::ctest summary"
-          colcon test --packages-select fastrtps --event-handlers=console_direct+ `
-            --merge-install --ctest-args $ctestargs --repeat until-pass:3 `
-            --timeout 300 --output-junit $junit
           "::endgroup::"
+
+          "::group::Build foonathan_memory"
+
+          cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}\${{ matrix.cmake-config }}\foonathan_memory -DCMAKE_BUILD_TYPE=${{ matrix.cmake-config }} -B ${{ github.workspace }}\build\foonathan_memory ${{ github.workspace }}\src\foonathan_memory
+
+          cmake --build ${{ github.workspace }}\build\foonathan_memory --config ${{ matrix.cmake-config }} --target install
+
+          "::endgroup::"
+
+          "::group::Build Fast CDR"
+
+          cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}\${{ matrix.cmake-config }}\fastcdr -DCMAKE_BUILD_TYPE=${{ matrix.cmake-config }} -B ${{ github.workspace }}\build\fastcdr ${{ github.workspace }}\src\fastcdr
+
+          cmake --build ${{ github.workspace }}\build\fastcdr --config ${{ matrix.cmake-config }} --target install
+
+          "::endgroup::"
+
+          "::group::Build Fast DDS"
+
+          cmake -DCMAKE_PREFIX_PATH='C:/Program Files/googletest/lib/cmake/GTest;${{ github.workspace }}\${{ matrix.cmake-config }}\foonathan_memory;${{ github.workspace }}\${{ matrix.cmake-config }}\fastcdr' -DGTest_DIR='C:/Program Files/googletest/lib/cmake/GTest' -DCMAKE_CXXFLAGS="/MP /WX" -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}\${{ matrix.cmake-config }}\fastrtps -DCMAKE_BUILD_TYPE=${{ matrix.cmake-config }} -DBUILD_DOCUMENTATION=OFF -DBUILD_SHARED_LIBS=ON -DCOMPILE_EXAMPLES=ON -DEPROSIMA_BUILD_TESTS=ON -DFASTDDS_ENFORCE_LOG_INFO=ON -DFASTDDS_PIM_API_TESTS=ON -DFASTDDS_STATISTICS=ON -DFASTRTPS_API_TESTS=OFF -DINSTALL_EXAMPLES=ON -DINSTALL_TOOLS=ON -DINTERNAL_DEBUG=ON -DNO_TLS=ON -DPERFORMANCE_TESTS=ON -DPROFILING_TESTS=OFF -DSECURITY=OFF -DSHM_TRANSPORT_DEFAULT=ON -DSTRICT_REALTIME=OFF -DSYSTEM_TESTS=ON -DTHIRDPARTY_Asio=FORCE -DTHIRDPARTY_fastcdr=OFF -DTHIRDPARTY_TinyXML2=FORCE -DTHIRDPARTY_UPDATE=ON ${{ inputs.cmake-args }} -B ${{ github.workspace }}\build\fastrtps ${{ github.workspace }}\src\fastrtps
+
+          cmake --build ${{ github.workspace }}\build\fastrtps --config ${{ matrix.cmake-config }} --target install
+
+          "::endgroup::"
+
+
+      # - name: Build
+      #   id: build
+      #   continue-on-error: false
+      #   uses: eProsima/eProsima-CI/windows/colcon_build@v0
+      #   with:
+      #     colcon_meta_file: ${{ github.workspace }}/ci.meta
+      #     colcon_build_args: --merge-install ${{ inputs.colcon-args }}
+      #     cmake_args: --no-warn-unused-cli ${{ inputs.cmake-args }}
+      #     cmake_args_default: -DCMAKE_PREFIX_PATH='C:/Program Files/googletest/lib/cmake/GTest' -DGTest_DIR='C:/Program Files/googletest/lib/cmake/GTest' -DCMAKE_CXXFLAGS="/MP /WX"
+      #     cmake_build_type: ${{ matrix.cmake-config }}
+      #     workspace: ${{ github.workspace }}
+
+      # - name: Test
+      #   if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-test') &&
+      #           (
+      #             steps.build.outcome == 'success' &&
+      #             (
+      #               steps.build.outputs.BuildWarningsErrors == 0 ||
+      #               contains(steps.build.outputs.BuildWarningsErrors, 'warning')
+      #             )
+      #           ) }}
+      #   id: test
+      #   run: |
+      #     # Create a junit file for test results
+      #     $junit = New-Item -Path ./junit.xml -ItemType File
+      #     'JUNIT_LOG=' + $junit.FullName | Out-File $Env:GITHUB_ENV -Append -Encoding OEM
+
+      #     # add ctest args
+      #     $ctestargs = '${{ inputs.ctest-args }}'.split(" ")
+
+      #     # Show the arguments
+      #     EchoArgs --packages-select fastrtps --event-handlers=console_direct+ `
+      #       --merge-install --ctest-args $ctestargs --repeat until-pass:3 `
+      #       --timeout 300 --output-junit $junit
+
+      #     # Run the testing
+      #     "::group::ctest summary"
+      #     colcon test --packages-select fastrtps --event-handlers=console_direct+ `
+      #       --merge-install --ctest-args $ctestargs --repeat until-pass:3 `
+      #       --timeout 300 --output-junit $junit
+      #     "::endgroup::"
