Refs #23253: Split windows workflow in different suites
Signed-off-by: Mario Dominguez <mariodominguez@eprosima.com>

diff --git a/.github/workflows/reusable-windows-ci.yml b/.github/workflows/reusable-windows-ci.yml
--- a/.github/workflows/reusable-windows-ci.yml
+++ b/.github/workflows/reusable-windows-ci.yml
@@ -33,13 +33,18 @@ on:
         required: false
         type: string
         default: 'RelWithDebInfo'
+      run-tests:
+        description: 'Run test suite of Fast DDS'
+        required: false
+        type: boolean
+        default: true
 
 defaults:
   run:
     shell: pwsh
 
 jobs:
-  reusable-windows-ci:
+  fastdds_build:
     runs-on: windows-2022
     strategy:
       fail-fast: false
@@ -98,34 +103,6 @@ jobs:
         with:
           packages: vcstool xmlschema psutil
 
-      - name: Update known hosts file for DNS resolver testing
-        if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-test') }}
-        run: |
-          $hostfile = "$Env:SystemRoot\system32\drivers" -replace "\\", "/"
-          $hostfile += "/etc/hosts"
-
-          # DNS entries to add
-          $new_entries = @{
-            "localhost.test" = "127.0.0.1", "::1"
-            "www.eprosima.com.test" = "154.56.134.194"
-            "www.acme.com.test" = "216.58.215.164", "2a00:1450:400e:803::2004"
-            "www.foo.com.test" = "140.82.121.4", "140.82.121.3"
-            "acme.org.test" = "ff1e::ffff:efff:1"
-          }
-
-          # Modify the file
-          $mod = { Param([string]$FilePath, [Hashtable]$Entries )
-            $entries.GetEnumerator() |
-              % { $hostname = $_.key; $_.value |
-              % { "{0,-25} {1}" -f $_, $hostname }} |
-              Out-File $filepath -Append
-          }
-
-          & $mod -FilePath $hostfile -Entries $new_entries
-
-          # Show the result
-          gc $hostfile
-
       - name: Get Fast CDR branch
         id: get_fastcdr_branch
         uses: eProsima/eProsima-CI/ubuntu/get_related_branch_from_repo@v0
@@ -163,26 +140,144 @@ jobs:
           colcon_build_args: ${{ inputs.colcon-args }}
           # The following Fast DDS CMake options need to be specified here instead of in the meta files
           # because they vary from platform to platform
+          cmake_args_default: ${{ inputs.cmake-args }} -T ${{ matrix.vs-toolset }} -DTHIRDPARTY_Asio=FORCE -DTHIRDPARTY_TinyXML2=FORCE -DTHIRDPARTY_fastcdr=OFF -DTHIRDPARTY_UPDATE=ON -DCOMPILE_EXAMPLES=ON -DEPROSIMA_EXTRA_CMAKE_CXX_FLAGS="/MP /WX"
+          cmake_build_type: ${{ inputs.cmake-config }}
+          workspace: ${{ github.workspace }}
+
+      - name: Upload build artifacts
+        uses: eProsima/eProsima-CI/external/upload-artifact@v0
+        with:
+          name: fastdds_build_${{ inputs.label }}
+          path: ${{ github.workspace }}
+
+  fastdds_test:
+    needs: fastdds_build
+    if: ${{ inputs.run-tests == true }}
+    name: fastdds_test (${{ matrix.cmake_build_type }}, ${{ matrix.test_filter }})
+    runs-on: windows-2022
+    strategy:
+      fail-fast: false
+      matrix:
+        vs-toolset:
+          - 'v142'
+        cmake_build_type:
+          - ${{ inputs.cmake-config }}
+        test_filter:
+          - 'blackbox'
+          - 'unittest'
+          - 'examples'
+        filter_expression_blackbox:
+          - 'BlackboxTests|ParticipantTests|SecureDiscoverServer|SimpleCommunication|system.'
+        filter_expression_examples:
+          - 'example_tests'
+
+    steps:
+      - name: Download build artifacts
+        uses: eProsima/eProsima-CI/external/download-artifact@v0
+        with:
+          name: fastdds_build_${{ inputs.label }}
+          path: ${{ github.workspace }}
+
+      - name: Update known hosts file for DNS resolver testing
+        run: |
+          $hostfile = "$Env:SystemRoot\system32\drivers" -replace "\\", "/"
+          $hostfile += "/etc/hosts"
+
+          # DNS entries to add
+          $new_entries = @{
+            "localhost.test" = "127.0.0.1", "::1"
+            "www.eprosima.com.test" = "154.56.134.194"
+            "www.acme.com.test" = "216.58.215.164", "2a00:1450:400e:803::2004"
+            "www.foo.com.test" = "140.82.121.4", "140.82.121.3"
+            "acme.org.test" = "ff1e::ffff:efff:1"
+          }
+
+          # Modify the file
+          $mod = { Param([string]$FilePath, [Hashtable]$Entries )
+            $entries.GetEnumerator() |
+              % { $hostname = $_.key; $_.value |
+              % { "{0,-25} {1}" -f $_, $hostname }} |
+              Out-File $filepath -Append
+          }
+
+          & $mod -FilePath $hostfile -Entries $new_entries
+
+          # Show the result
+          gc $hostfile
+
+      - name: Install Fix Python version
+        uses: eProsima/eProsima-CI/external/setup-python@v0
+        with:
+          python-version: '3.11'
+
+      - name: Get minimum supported version of CMake
+        uses: eProsima/eProsima-CI/external/get-cmake@v0
+        with:
+          cmakeVersion: '3.22.6'
+
+      - name: Install OpenSSL
+        uses: eProsima/eprosima-CI/windows/install_openssl@v0
+        with:
+          version: '3.1.1'
+
+      - name: Update OpenSSL environment variables
+        run: |
+          # Update the environment
+          if (Test-Path -Path $Env:ProgramW6432\OpenSSL)
+          {
+            "OPENSSL64_ROOT=$Env:ProgramW6432\OpenSSL" | Out-File $Env:GITHUB_ENV -Append -Encoding OEM
+          }
+          elseif (Test-Path -Path $Env:ProgramW6432\OpenSSL-Win)
+          {
+            "OPENSSL64_ROOT=$Env:ProgramW6432\OpenSSL-Win" | Out-File $Env:GITHUB_ENV -Append -Encoding OEM
+          }
+          elseif (Test-Path -Path $Env:ProgramW6432\OpenSSL-Win64)
+          {
+            "OPENSSL64_ROOT=$Env:ProgramW6432\OpenSSL-Win64" | Out-File $Env:GITHUB_ENV -Append -Encoding OEM
+          }
+          else
+          {
+            Write-Error -Message "Cannot find OpenSSL installation."
+            exit 1
+          }
+
+      - name: Install colcon
+        uses: eProsima/eProsima-CI/windows/install_colcon@v0
+
+      - name: Install Python dependencies
+        uses: eProsima/eProsima-CI/windows/install_python_packages@v0
+        with:
+          packages: vcstool xmlschema psutil
+
+      #Build Windows examples testing docker image
+      - name: Build with example testing
+        if: ${{ matrix.test_filter == 'examples' }}
+        continue-on-error: false
+        uses: eProsima/eProsima-CI/windows/colcon_build@v0
+        with:
+          colcon_meta_file: ${{ github.workspace }}\src\fastdds\.github\workflows\config\fastdds_build.meta ${{ github.workspace }}\src\fastdds\.github\workflows\config\fastdds_test.meta
+          colcon_build_args: ${{ inputs.colcon-args }}
+          # The following Fast DDS CMake options need to be specified here instead of in the meta files
+          # because they vary from platform to platform
           cmake_args_default: ${{ inputs.cmake-args }} -T ${{ matrix.vs-toolset }} -DTHIRDPARTY_Asio=FORCE -DTHIRDPARTY_TinyXML2=FORCE -DTHIRDPARTY_fastcdr=OFF -DTHIRDPARTY_UPDATE=ON -DFASTDDS_EXAMPLE_TESTS=ON -DEPROSIMA_EXTRA_CMAKE_CXX_FLAGS="/MP /WX"
           cmake_build_type: ${{ inputs.cmake-config }}
           workspace: ${{ github.workspace }}
 
       - name: Test
-        if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-test') }}
         id: test
         uses: eProsima/eProsima-CI/windows/colcon_test@v0
         with:
           colcon_meta_file: ${{ github.workspace }}\src\fastdds\.github\workflows\config\fastdds_test.meta
           colcon_test_args: ${{ inputs.colcon-args }}
           colcon_test_args_default: --event-handlers=console_direct+
-          ctest_args: ${{ inputs.ctest-args }}
+          ctest_args: ${{ inputs.ctest-args }} ${{ matrix.test_filter == 'blackbox' && format('-R "{0}"', matrix.filter_expression_blackbox) || matrix.test_filter == 'examples' && format('-R "{0}"', matrix.filter_expression_examples) || format('-E "{0}|{1}" -j 4', matrix.filter_expression_blackbox , matrix.filter_expression_examples) }}
           packages_names: fastdds
           workspace: ${{ github.workspace }}
           test_report_artifact: ${{ format('test_report_{0}_{1}_{2}', inputs.label, github.job, join(matrix.*, '_')) }}
 
       - name: Test summary
         uses: eProsima/eProsima-CI/windows/junit_summary@v0
-        if: ${{ !cancelled() && !contains(github.event.pull_request.labels.*.name, 'no-test') }}
+        if: ${{ !cancelled() }}
         with:
           junit_reports_dir: "${{ steps.test.outputs.ctest_results_path }}"
           print_summary: 'True'
