Refs 15025. Update thread sanitizer workflow.
Signed-off-by: Miguel Barro <miguelbarro@eprosima.com>

diff --git a/.github/workflows/thread-sanitizer.yaml b/.github/workflows/thread-sanitizer.yaml
--- a/.github/workflows/thread-sanitizer.yaml
+++ b/.github/workflows/thread-sanitizer.yaml
@@ -3,10 +3,10 @@ on:
   workflow_dispatch:
   push:
     branches:
-      - 'feature/tsan/fixes'
+      - 'master'
   pull_request:
     branches:
-      - 'feature/tsan/fixes'
+      - 'master'
 env:
   TSAN_OPTIONS: second_deadlock_stack=1
   # ubuntu host doesn't have an environment SHELL value (docker and vm images does)???
@@ -46,7 +46,7 @@ jobs:
           cd ws
           cmake -DCMAKE_MODULE_PATH="$(pwd)/sanitizers-cmake/cmake" -DCMAKE_INSTALL_PREFIX="./install" `
                 -DBUILD_GMOCK=ON -DSANITIZE_THREAD=ON -DCMAKE_BUILD_TYPE=Debug `
-                -DCMAKE_VERBOSE_MAKEFILE=ON -B ./build/googletest ./googletest 
+                -DCMAKE_VERBOSE_MAKEFILE=ON -B ./build/googletest ./googletest
           cmake --build ./build/googletest --target install --verbose
 
       - name: Download Fast-CDR and make it sanitizer aware
@@ -63,7 +63,7 @@ jobs:
           cd ws
           cmake -DCMAKE_INSTALL_PREFIX="./install" -DCMAKE_PREFIX_PATH="./install" `
                 -DCMAKE_MODULE_PATH="$(pwd)/sanitizers-cmake/cmake" -DCMAKE_VERBOSE_MAKEFILE=ON `
-                -DSANITIZE_THREAD=ON -DCMAKE_BUILD_TYPE=Debug -B ./build/fastcdr ./Fast-CDR 
+                -DSANITIZE_THREAD=ON -DCMAKE_BUILD_TYPE=Debug -B ./build/fastcdr ./Fast-CDR
           cmake --build ./build/fastcdr --target install --verbose
 
       - name: Download foonathan/memory and make it sanitizer aware
@@ -95,7 +95,7 @@ jobs:
           git diff --name-only HEAD~1
           git remote add efork https://github.com/MiguelBarro/Fast-DDS.git
           git fetch efork
-          git merge --no-edit efork/bugfix/add_sanitizer_support | Out-Null
+          git merge --no-edit efork/bugfix/add_sanitizer_support
 
       - name: Build & install Fast-DDS
         run: |
@@ -107,7 +107,9 @@ jobs:
                 -DCMAKE_BUILD_TYPE=Debug -B ./build/fastdds ./Fast-DDS
           # Create a symlink to the reports folder
           $report_dir = gci -Path ./build/fastdds -Attributes D |
-            ? Name -like "$(Get-Date -Format 'MMMM-dd-yyyy')*" 
+            ? Name -like "$(Get-Date -Format 'MMMM-dd-yyyy')*"
+          $report_dir = Join-Path $report_dir tsan | gi
+          echo "report folder is: $report_dir"
           New-Item -ItemType SymbolicLink -Target $report_dir -Path ./build/fastdds/reports
           cmake --build ./build/fastdds --target install -j 2 --verbose
 
@@ -116,9 +118,11 @@ jobs:
           cd ws/build/fastdds
           ctest --timeout 30 -j 2 -V
           # ctest fails if sanitizer reports are present
-          $LASTEXITCODE=0 
+          $LASTEXITCODE=0
 
       - name: Process sanitizer reports
+        id: summary
+        continue-on-error: true
         run: |
           # Create a dir for the exports
           $exports = New-Item -ItemType Directory -Path ./ws/exports
@@ -127,7 +131,7 @@ jobs:
           # Install the report parser module
           Find-Module -Repository PSGallery -Name SanReportParser | Install-Module -Scope CurrentUser -Force
           # Parse the report files
-          $rp = Show-Tsan (gci) 
+          $rp = Show-Tsan (gci)
           # filter duplicates
           $rp = $rp | group md5hash | % { $_.group[0] }
           # Export raw data
@@ -135,8 +139,8 @@ jobs:
           # Group the reports by issue
           $g = $rp | group fuzzhash
           # Split up deadlocks and race reports
-          $gd = $rp | ? type -match dead | group fuzzhash 
-          $gr = $rp | ? type -match race | group fuzzhash 
+          $gd = $rp | ? type -match dead | group fuzzhash
+          $gr = $rp | ? type -match race | group fuzzhash
           # Simplified deadlock summary (only one representative report and tests associated)
           $sd = $gd | Sort-Object count -desc | select @{l="fuzzhash";e="name"}, count, `
               @{l="échantillon";e={$_.group[0].report}}, @{l="tests"; `
@@ -157,12 +161,24 @@ jobs:
           # Keep a file per issue
           $dir = New-Item -ItemType Directory -Path (Join-Path $exports reports)
           & {$sd; $sr} | % { $_.échantillon | Out-File (Join-Path $dir "$($_.fuzzhash).tsan") }
-          # Zip an artifact
-          popd
-          gci $exports | Compress-Archive -DestinationPath ./ws/tsan_reports.zip 
+          # Create a summary table
+          @{Type="Deadlock";Failed=$sd.count;Hashes=$sd.fuzzhash},
+          @{Type="Data race";Failed=$sr.count;Hashes=$sr.fuzzhash} |
+            % { $_.Summary = $_.Hashes | select -First 5  | Join-String -Separator ", "
+                if ($_.Hashes.count -gt 5 ) {
+                    $_.Summary += ", ..." }; $_ } |
+              % { [PSCustomObject]$_} |
+              New-MDTable -Columns ([ordered]@{Failed=$null;Type=$null;Summary=$null}) |
+              Out-File $Env:GITHUB_STEP_SUMMARY
+          # The step fails on new deadlocks
+          $LASTEXITCODE=$sd.count
+
+      - name: Check on failures
+        if: ${{ steps.summary.outcome }} == 'failure'
+        run: exit 1
 
       - name: Archive sanitation results
         uses: actions/upload-artifact@v3
         with:
             name: sanitation-report
-            path: /home/runner/work/ws/tsan_reports.zip
+            path: /home/runner/work/ws/exports/*
